apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoibXVzdGFmYXNlZ2YiLCJwYXNzd29yZCI6Imdob18xYW1aeFlzdWJCd3BFTW56MjB6aU03Nk5SR1dvcmcyYXpPYzIiLCJhdXRoIjoiYlhWemRHRm1ZWE5sWjJZNloyaHZYekZoYlZwNFdYTjFZa0ozY0VWTmJub3lNSHBwVFRjMlRsSkhWMjl5WnpKaGVrOWpNZz09In19fQ==
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
